### ISSUE TITLE
更换cookie的问题

### ISSUE THREAD

**Issue by chenyibai9527** [Alvin-Liu/suno-music-generator#3]
大佬提一个建议：现在探索是当前cookie所在账号生成的歌曲，能不能改成suno官方推荐的歌曲啊？
另外，clerk 登录时指向的clerk.shared.lcl.dev 生产环境也是这样吗，还是我的配置有问题
![image](https://github.com/Alvin-Liu/suno-music-generator/assets/107304274/4d73c234-b454-4d69-b4be-796d0e3d5b5c)
最后，如果想要清空当前探索中的歌曲应该怎么做，好像更换cookie没用。。

**Comment by Alvin-Liu** [comment]
1. suno 官方推荐的歌曲这个可以加一个，我有空弄一下
2. clerk 这个我还真没注意，要研究下
3. 清空探索中的歌曲可以把你数据库的music表内容清了就可以了
